[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }

[[language]]
name = "go"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sh", args = [ "-c", "gofumpt <&0 | goimports -local \"github.com/formulatehq\"" ] }
